### ISSUE TITLE
Return error(s) where possible please

### ISSUE THREAD

**Issue by tadvi** [balacode/one-file-pdf#4]
How to know that SaveFile failed except by reading log?
Please return errors instead of logging them. 

Application code should log, libraries should not log but return errors.

Other than that good library looking forward using it. Thanks.

**Comment by balacode** [comment]
Thank you for valuable input! I'm changing `SaveFile()` to return `error` instead of `*PDF`.

IO can have errors beyond the control of the library and because `SaveFile()` is normally the last method called on PDF, it does not need to return *PDF for method chaining.

Most other methods log logic errors (e.g. "unknown page size") and return *PDF. To change them to return error would mean to remove method chaining. I'm thinking of another means to query for errors in these cases: perhaps a pdf.Err() method that is set to an instance of the last error.

You can also redefine PDFErrorHandler to another function with the same signature as fmt.Println: 
`func(a ...interface{}) (n int, err error)`. (However, soon the error handler will be set per PDF instance, not globally.)

Your additional suggestions are welcome.

**Comment by tadvi** [comment]
Do you have to have method chaining?

pdf.Err() would probably be ok, as long as errors are returned instead of logging.

**Comment by balacode** [comment]
Chaining is a good feature to have:
```go
pdf.SetXY(5, 5).SetColor("red").DrawText("hello")
```
without chaining, will be:
```go
pdf.SetXY(5,5)
pdf.SetColor("red")
pdf.DrawText("hello")
```
... and you can't put all these statements on one line because 'go fmt' would split them into many lines.
I thought of returning (*PDF, error) but that won't work: 
```
multiple-value pdf.SetX() in single-value context
```
Please excuse my long explanation, its so that anyone who looks at this issue considers it,

**Comment by tadvi** [comment]
If you must have chaining then store first error value inside pdf.Err. That way it would be reachable after chain of calls. Thanks.

**Comment by balacode** [comment]
I've changed SaveFile() to return error now, and some other changes (see changelog). Yet to add Err(), but soon. Again, thank you for pointing it out.

**Comment by balacode** [comment]
Hi, I've created some error handling methods in commit fd06c6f:

Clean() *PDF - clears all accumulated errors.
Errors() []error - returns a slice of all accumulated errors
PullError() error - removes and returns the first error from the errors collection

In the past few days I've made some changes to remove unnecessary error conditions that should never occur in the first place. For example, the checks for a page being active, since now there is always an active page.

Other changes I'm planning soon:

* To add the name of the method to each error message, so you can know
  where in the chain the error occurred.
  
- To remove some other spurious error checks: e.g. the "Rune out of range" error in textWidthPt1000() that should never happen in the first place, because we're not using Unicode yet, and even then it won't be needed.

- There may be minor changes/fixes to error handling over the weekend.

**Comment by balacode** [comment]
* Error messages now include the name of the method that produced the error
* Clean(), Errors() and PullError() have unit tests, work as expected
